# Generated by Django 3.1.3 on 2020-11-18 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixinapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemslist',
            name='itemname',
            field=models.CharField(default='book', max_length=100),
            preserve_default=False,
        ),
    ]
